### ISSUE TITLE
Error when running this module : Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by ankesh-m** [h2non/videoshow#27]
I am using videoshow module to generate video but it is throwing error when i am running the module.
Here is the code which i am using :

    createVideo: function(req,res,next) { 
        var images = [
              '1.jpg',
              '2.jpg',
              '3.jpg',
              '4.jpg'
        ]

        var videoOptions = {
          fps: 25,
          loop: 5, // seconds
          transition: true,
          transitionDuration: 1, // seconds
          videoBitrate: 1024,
          videoCodec: 'libx264',
          size: '640x?',
          audioBitrate: '128k',
          audioChannels: 2,
          format: 'mp4'
        }

        videoshow(images, videoOptions)
          .save('video.mp4')
          .on('start', function (command) {
            console.log('ffmpeg process started:', command)
          })
          .on('error', function (err, stdout, stderr) {
            console.error('Error:', err)
            console.error('ffmpeg stderr:', stderr)
          })
          .on('end', function (output) {
            console.error('Video created in:', output)
          })
    }

When i am running the code it is showing the error below : 

    Error: [Error: Cannot find ffmpeg]
    ffmpeg stderr: undefined

**Comment by h2non** [comment]
Please, install ffmpeg first and make sure it's PATH accessible.

**Comment by ankesh-m** [comment]
I have installed ffmpeg but how can i check PATH accessible. I am using Ubuntu.
    npm install ffmpeg

**Comment by h2non** [comment]
Please, follow this instructions:
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

**Comment by ankesh-m** [comment]
oh, i got it. Thanks
