### ISSUE TITLE
Generate video from images with different dimensions

### ISSUE THREAD

**Issue by leo-mck** [h2non/videoshow#29]
with ffmpeg I can create a video with images with multiple different dimensions calling this:

`ffmpeg -r 30 -i %0d.jpg -vf "scale=1920:1080,format=yuv420p" -codec:v libx264 out.mp4`

Is it possible to add the  `-vf "scale=1920:1080,format=yuv420p"` to the videoshow command? 
I tried to just pass to the options 
`filters: [{ filter: 'scale', options: [640, -1] }]  ` but this did not worked, It still causes an error when passing images with different dimensions:

`Error: [Error: ffmpeg exited with code 1: Error configuring complex filters.
Invalid argument
]`

Thanks for the amazing work on this!

**Comment by h2non** [comment]
Try passing it as complex filters: https://github.com/h2non/videoshow#videoshowcomplexfilterfilter

**Comment by leo-mck** [comment]
Hi, thank you for your help. In the end, my problem was that the partial videos could not be joined together because they had a different SAR when images had different dimensions. I was able to solve it passing the Images as an array of objects containing the path and a filter "setsar=sar=1/1".

**Comment by jaleelg** [comment]
Hi how can I get this done with videoshow? How do I use the complex filters? I am getting the same error when I try to use different dimension photos.

**Comment by yoga80** [comment]
Is there any sample. I have tried different options. Could it be illustrated how we could allow images of multi-dimensions to be handled.
