### ISSUE TITLE
Video does not play on mobile

### ISSUE THREAD

**Issue by sbsomya** [h2non/videoshow#30]
Hi 
I created a video using videoshow and video is playing on laptop but not on mobile
The parameters provided are below

```
                fps: 25,
                loop: 0.1, // seconds
                transition: false,
                videoBitrate: 1024,
                videoCodec: 'libx264',
                size: '640x?',
                audioBitrate: '128k',
                audioChannels: 2,
                format: 'mp4'
```

**Comment by sbsomya** [comment]
Added this line in mergeParts function line:77

options.push("-pix_fmt yuv420p");//works on all mobiles
Then it starting to work on all mobiles

**Comment by h2non** [comment]
Feel free to do a PR.

**Comment by thomaswelton** [comment]
@sbsomya if you got this to work can you submit a PR please?
