### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Manisha-Bajaj** [h2non/videoshow#36]
I am new in node.js , I want to create web application which takes images and audio and will generate video corresponding to that.
I have view your videoshow and thought that is best suited for my need but can you guide me how to implement that code for dedicated purpose.

Kindly response as soon as possible as I am already very late

**Comment by h2non** [comment]
You can simply see and run one of the examples, such as:
https://github.com/h2non/videoshow/blob/master/examples/audio.js

Then simply run it via `node`:
```js
node examples/audio.js
```

You must customize the options you want for the video rendering.
See the API here:
https://github.com/h2non/videoshow#api

**Comment by Manisha-Bajaj** [comment]
![capture](https://cloud.githubusercontent.com/assets/13680649/20521477/3f1aa130-b0cd-11e6-9c37-db09b2cd25c2.PNG)

I am facing these errors

**Comment by h2non** [comment]
Run `npm install`

**Comment by Manisha-Bajaj** [comment]
![image](https://cloud.githubusercontent.com/assets/13680649/20522160/9b66f206-b0d0-11e6-836e-cb02ee69d7df.png)

**Comment by Manisha-Bajaj** [comment]
Kindly reply if you understand the problem

**Comment by h2non** [comment]
You must install `ffmpeg` in your system. See:
https://ffmpeg.org/download.html

**Comment by Manisha-Bajaj** [comment]
Thank you so much

**Comment by Manisha-Bajaj** [comment]
Video has been created successfully but it is just audio , but there is no any image in that video as code contains image, then why video does not show images

**Comment by Manisha-Bajaj** [comment]
Everything is working good , thank you so much for helping me .
It`s pleasure to use your code for my project.
