### ISSUE TITLE
captions.js example  throw new Error('No input specified');

### ISSUE THREAD

**Issue by greatyaqi** [h2non/videoshow#39]
hi.I'm from project operates example,  and audio.js no problem,but captions.js example  throw new Error('No input specified'). can you help me? by the way.I have and demand is image  turning the video.Image requires animation effects, not only effects that fade in shallow.

**Comment by oknoorap** [comment]
+1 I've got the same error here.

**Comment by bushev** [comment]
@greatyaqi I'm not pretty sure. Сommenting [this line](https://github.com/h2non/videoshow/blob/master/lib/videoshow.js#L106) helps me.

**Comment by h2non** [comment]
Sadly, that line was introduced in another user MR. My fault during code review. I will fix that and a new release.

**Comment by h2non** [comment]
`videoshow@0.1.11` is out available in `npm`. Try it again.

**Comment by bushev** [comment]
@h2non Works great! 👍
