### ISSUE TITLE
How to change speed to ultrafast? [Help request]

### ISSUE THREAD

**Issue by isaachinman** [h2non/videoshow#43]
On [this page](https://trac.ffmpeg.org/wiki/Encode/H.264) of the ffmpeg docs, it indicates there are several presets for render configs that affect speed.

I am using `videoshow` in a personal project and have noticed extremely long render times, up to 20 minutes for a 6 minute video, etc. How is it possible to use one of these speed presets with `videoshow`?

Thanks.

**Comment by h2non** [comment]
Time is not `ffmpeg` best friend, especially for video processing.
The only way I see you can speed up the process a bit would using more powerful hardware.

**Comment by isaachinman** [comment]
No, there is literally an `ultrafast` preset, I am just asking how I can pass it via this project. I am using a top line 2015 MBP so I would expect to be able to render simple videos in at least a 1:1 ratio of duration.

Thanks either way, it is a nice project!

**Comment by glmn** [comment]
Try to use  [videoshow#options](https://github.com/h2non/videoshow#videoshowoptionsoptions)

```
videoshow([ 'image1.jpg', 'image2.jpg', 'image3.jpg'])
  .save('video.mp4')
  .options(['-preset ultrafast'])
  .on('error', function () {})
  .on('end', function () {})```
