### ISSUE TITLE
animated gif support?

### ISSUE THREAD

**Issue by fat** [h2non/videoshow#46]
Noticed in your readme that you mentioned their was `.gif` support - but not sure if that included animated gifs.

I tried changing your audio example to include the chuck norris gif:

<img width="494" alt="screen shot 2017-07-11 at 4 03 36 pm" src="https://user-images.githubusercontent.com/169705/28094619-a1035a8c-6652-11e7-8d5b-0ce2f97bff73.png">

But i get the following error:

```
$ node audio.js 
Error: Error: ffmpeg exited with code 1: Option loop not found.
at ChildProcess.<anonymous> (/Users/fat/Workspace/videoshow/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

Is there something else i need to change? or is this not supported. Thnks!

**Comment by fat** [comment]
ah ok the problem is that the `loop` option isn't supported with `.gif`… trying to think of a cool workaround

**Comment by ZuzooVn** [comment]
Do you find the solution?

**Comment by fat** [comment]
Hey,

I ended up just writing my own lib for this - but if you're interested… basically what you need to do is use the concat method: https://video.stackexchange.com/questions/12905/repeat-loop-input-video-with-ffmpeg/12906#12906

So what i do is:

1. determine the total duration (say 25seconds) 
2. determine the total length of my gif (say 10 seconds) 
3. add enough gifs to the concat `.txt` to exceed my specified end duration (in this case 3 loops - or 30 seconds)
4. trim the total output back down to 25 seconds

It's quite a bit of work annoyingly :/

I'll go ahead and close this issue for you - but you might want to consider just removing the `.gif` support from your readme

**Comment by h2non** [comment]
Cool. I never had that requirement, but thanks for sharing that.
