### ISSUE TITLE
Examples captions.js, logo.js, and subtitles.js throw error

### ISSUE THREAD

**Issue by AppGodOrg** [h2non/videoshow#54]
I cloned this repository.

Examples captions.js, logo.js, and subtitles.js throw this error:

> Error: Error: ffmpeg exited with code 1: Error reinitializing filters!
> Failed to inject frame into filter network: Invalid argument
> Error while processing the decoded data for stream #0:0
> Conversion failed!
> 
>     at ChildProcess.<anonymous> (/Users/adam/Apps/affirmations/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

If you cannot replicate this, let me know what information you need from me.

Thanks!

**Comment by h2non** [comment]
Ensure your ffmpeg compilation has all the required library bindings, such as audio codecs, video and subtitles.

**Comment by AppGodOrg** [comment]
YEAP. I was missing --enable-libfreetype.

**Comment by remorses** [comment]
How can I add that?
