### ISSUE TITLE
Help with image and video settings

### ISSUE THREAD

**Issue by akralj** [h2non/videoshow#61]
Hi, thanks for this great library.
Not knowing much about video processing, I would need some advice how to create videos with a lot of images (around 1000) and a video length of 60 seconds.
i use this settings and it takes forever till the images are copied into the tmp folder.
```
fps: 25,
loop: 0.06 ,
transition: false,
videoBitrate: 1024,
videoCodec: "libx264",
size: "100%",
format: "mp4",
pixelFormat: "yuv420p"
```
I get the images from a camera as jpegs, where I can choose the resolution.
If someone could be so kind to post a feasible image size + video settings, so the process does not take like 1/2 hour.
Thanks a lot

**Comment by michaelwschultz** [comment]
@akralj just combing through the issues here and thought I'd try and answer your question. I know it's two years late, but maybe you're still curious... if not, maybe just close this issue.

I'm wondering how big your photos are in size? Are you taking the photos from a DSLR camera or your webcam? My thought is that you may want to compress the images before running videoshow on them. This should speed up the conversion process. This could also depend on your hardware. Hope that helps.

**Comment by akralj** [comment]
Thanks for your comment. I solved it by using fffmpeg directly.
