### ISSUE TITLE
Is there a way to use multiple audio files?

### ISSUE THREAD

**Issue by Snazzyham** [h2non/videoshow#81]
Sorry if this is somewhere in the docs and I'm just not seeing it, tried looking around. 

Essentially, what I want to do is have multiple audio files for multiple images, because they're like voiceovers for each image. For example, imageA has it's own voiceover, say VoiceoverA, and I wan't imageA to be shown for the duration of VoiceoverA, and then move on to imageB and VoiceverB. 

Is something like that possible with this library? Or do I have to make multiple videos and store them in an array, and then use something like `ffmpeg-concat` to concatenate them together. 

Thanks in advance!

**Comment by h2non** [comment]
You can use [audioconcat](https://github.com/h2non/audioconcat) or a similar tool and then use the output audio file in `videoshow`.
