### ISSUE TITLE
Is it possible to use Buffers instead of paths?

### ISSUE THREAD

**Issue by bali182** [h2non/videoshow#95]
I'm trying to generate videos from dynamically generated images, in my use case there is no reason to write these images to disk. Is there a way to provide Buffers (or any other in-memory representation as input)?

**Comment by h2non** [comment]
No, it is not, basically because of the way the ffmpeg bindings context-switching works. You may use node.js streams in some cases, but you will have to fork the repository and do the needed adjustments:
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#specifying-inputs

**Comment by Sitronik** [comment]
I managed to do with base64 dynamic images
In this example I am creating a readable stream, you can try to pass your buffer to readableStream

```js
const Readable = require('stream').Readable

const base64 = 'base64 image here';

var matches = base64.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
const imgBuffer = Buffer.from(matches[2], 'base64')
const readableStream = new Readable()

readableStream.push(imgBuffer)
readableStream.push(null)

// for videoshow
const images = [{path: readableStream}]
```
